version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  app:
    build: .
    ports:
      - '8081:8081'
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      JWT_SECRET: ${JWT_SECRET}
      JAVA_OPTS: -Xmx512m